/*
游戏内的所需要使用的全局静态变量
*/

let C: any = {};

C.WX = {};
C.WX.AC_INIT = 100;
C.WX.AC_TEST = 101;
C.WX.AC_STORAGE = 102;
C.WX.AC_SCROLL_V = 103;
C.WX.AC_SCROLL_H = 104;
C.WX.AC_F_STAR_FETCH = 121;
C.WX.AC_G_STAR_FETCH = 122;
C.WX.AC_F_STAR_SETTLE = 123;
C.WX.AC_F_RUSSIA_FETCH = 131;
C.WX.AC_G_RUSSIA_FETCH = 132;
C.WX.AC_F_RUSSIA_SETTLE = 133;
C.WX.AC_F_HAUL_FETCH = 141;
C.WX.AC_G_HAUL_FETCH = 142;
C.WX.AC_F_DIGIT_FETCH = 151;
C.WX.AC_G_DIGIT_FETCH = 152;
C.WX.AC_F_UNION_FETCH = 161;
C.WX.AC_G_UNION_FETCH = 162;
C.WX.AC_F_UNION_SETTLE = 163;
C.WX.AC_F_POP_FETCH = 171;
C.WX.AC_G_POP_FETCH = 172;


C.REVIVE_MODE = {};
C.REVIVE_MODE.NONE = -1;
C.REVIVE_MODE.FREE = 0;
C.REVIVE_MODE.SHARE = 1;
C.REVIVE_MODE.VIDEO = 2;

C.GAME_MODE = {};
C.GAME_MODE.NONE = -1;
C.GAME_MODE.STAR = 0;
C.GAME_MODE.RUSSIA = 1;
C.GAME_MODE.HAUL = 2;
C.GAME_MODE.UNION = 3;
C.GAME_MODE.DIGIT = 4; //数字三消
C.GAME_MODE.POP = 5; //开心消消乐模式

C.ITEM_MODE = {};
C.ITEM_MODE.MIX = 0;
C.ITEM_MODE.DYE = 1;
C.ITEM_MODE.BOMB = 2;
C.ITEM_MODE.CHARM = 3;

C.LIKE = {};
C.LIKE.COOL = 5;
C.LIKE.PERFECT = 10;
C.LIKE.SUPERSTAR = 15;
C.LIKE.UNION_COOL = 10;
C.LIKE.UNION_PERFECT = 15;
C.LIKE.UNION_SUPERSTAR = 20;


let GameConstant = C;
export default GameConstant;